const { VanillaExtractPlugin } = require("@vanilla-extract/webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  reactScriptsVersion: "react-scripts",
  webpack: {
    plugins: [new VanillaExtractPlugin(), new MiniCssExtractPlugin()],
    module: {
      rules: [
        {
          test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: require.resolve("css-loader"),
              options: {
                url: false, // Required as image imports should be handled via JS/TS import statements
              },
            },
          ],
        },
      ],
    },
  },
  jest: {
    preset: "ts-jest",
    testEnvironment: "node",
    testMatch: ["**/__tests__/**/*.ts?(x)", "**/?(*.)+(test).ts?(x)"],
    globals: {
      "ts-jest": {
        diagnostics: {
          warnOnly: true,
        },
      },
      babelConfig: {
        plugins: ["@vanilla-extract/babel-plugin"],
      },
    },
  },
};
